### PR TITLE
Debian based on upstream

### PR DESCRIPTION
**Pull request by gerddie**
Hi Yaroslav, 

My changes so far: 
- Add test data in debian/testdata 
- add soversion and version to libraries to remove lintian error: 
  _sharedobject-in-library-directory-missing-soname_
- move to debhelper 9 
- changed _libboost1.49-dev_ to version-less _libboost-dev_

The result is a package with the remaining lintian warnings and errors: 

```
lintian ants_2.0.0-1_amd64.deb    
```
- E: ants: _empty-manual-page_ usr/share/man/man1/GetMeshAndTopology.1.gz
- E: ants: _shell-script-fails-syntax-check_ usr/lib/ants/unbiased_pairwise_registration_with_aux_images.sh
  - See also https://github.com/stnava/ANTs/issues/70
  - For the moment we could just delete this script
- E: ants: _shell-script-fails-syntax-check_ usr/lib/ants/unbiased_pairwise_registration_with_aux_images.she
  - A left over from sed, I guess, why, I don't know. 
- W: ants: _executable-not-elf-or-script_ usr/share/modules/modulefiles/ants/ants.environment-modules
  This is something you add. Hence you should know if this needs to be corrected or overridden 
- N: 84 tags overridden (84 warnings),  Overrides are 
  - 7x errors in manpages. 
  - package-name-doesnt-match-sonames
  - non-dev-pkg-with-shlib-symlink

For the last one I could remove the *.so files from the install. Since there is no -dev package, the shared libraries with the version numbers should suffice. 

As for the test data. It is currently ~1MB uncompressed. I happily dig into packaging it into a separate tarball when I have more time, right now I don't see how git-buildpackage and a secondary source tarball may work together and would prefer to leave it in the debian\* part. Maybe when upstream is willing to add the data to their tarball the problem will resolve itself :) 

best 
Gert

### CODE REVIEW

**Comment by yarikoptic** [comment]
NICE -- thanks!

would you be so kind to clean it tiny bit up -- there should be no applied patches (git rebase -i 495eea5, dropping some commits and forcing the push could be the way to get it)

envir modules files -- please fix permissions, shouldn't be exec

.so -- versioned indeed should be enough (but verify please) -- thanks

**Comment by gerddie** [comment]
Done.  I test run the ANTS command and it run without the *.so files (as it should). Same for a random sample out of /usr/lib/ants/ 

I didn't have time to test the very last two patches that remove the sed backup files. I'm running the build right now, but will only be able to check the result tomorrow.

**Comment by gerddie** [comment]
As far as I can see the package builds and installs properly, two lintian errors are left 

*E: ants: empty-manual-page usr/share/man/man1/GetMeshAndTopology.1.gz
*E: ants: shell-script-fails-syntax-check usr/lib/ants/unbiased_pairwise_registration_with_aux_images.sh

and a lot of pedantic messages.

**Comment by gerddie** [comment]
I'm not even sure if libtiff is requires at all, since ANTS uses ITK for image IO. Anyway, on wheezy libtiff5-dev conflicts with libvtk5-dev and libtiff-dev is provided by the libtiff4-dev which is compatible with the available version of vtk.

**Comment by yarikoptic** [comment]
On Fri, 28 Feb 2014, Gert Wollny wrote:

>    I'm not even sure if libtiff is requires at all, since ANTS uses ITK for
>    image IO. 

I should have placed more informative commit msg I guess -- but I did
add it just recently (Wed Dec 11 15:35:27 2013) so must have run into a
failing build and figured it would be the one ;)

> Anyway, on wheezy libtiff5-dev conflicts with libvtk5-dev and
>    libtiff-dev is provided by the libtiff4-dev which is compatible with the
>    available version of vtk.

have you tried building it on wheezy without libtiff5-dev dependency?
may be indeed libtiff5-dev is not needed?

## 

Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Senior Research Associate,     Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
I had impression that you have tuned up the watch file... may be
left non-committed?

## 

Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Senior Research Associate,     Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by gerddie** [comment]
- I built with dep libtiff4-dev on wheezy, and libtiff5-dev on jessie - and both cases would be covered by libtiff-dev, but I think cmake doesn't really look for it. 
- I didn't touch the watch file, I only sent a link in an email where a real tarball can be found on github.

**Comment by yarikoptic** [comment]
ok -- thanks

meanwhile I just initiated the package build 

let's wait to see what comes out of it

On Fri, 28 Feb 2014, Gert Wollny wrote:

> ```
>  * I built with dep libtiff4-dev on wheezy, and libtiff5-dev on jessie -
>    and both cases would be covered by libtiff-dev, but I think cmake
>    doesn't really look for it.
>  * I didn't touch the watch file, I only sent a link in an email where a
>    real tarball can be found on github.
> ```
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
> References
> 
>    Visible links
> 1. https://github.com/neurodebian/ANTs/pull/1#issuecomment-36357964

## 

Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Senior Research Associate,     Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Pull request merged**
